### ISSUE TITLE
Consolidate CI platforms to one: AppVeyor

### ISSUE THREAD

**Issue by lvillani** [just-install/dnsconfig#3]
I see that we are using two CI platforms at the moment:

* AppVeyor for the just-install repository.
* Travis for everything else (including this repository).

I would like to consolidate our CI platforms to only use AppVeyor, since this is a Windows-centric tool. 

Unless there's a strong need to run some tasks on a Unix-based environment (besides familiarity) I think it's better for us to reduce the cognitive load across wildly different platforms/services (this goes hand-in-and with https://github.com/just-install/just-install/issues/274).

**Comment by pgaskin** [comment]
I really like Travis though, and I'm way more familiar with it. Also, I usually work on jiup-go from Linux, but it should work fine with Windows. Other than that, there shouldn't be any issue in switching.

**Comment by lvillani** [comment]
I see your point, let's maintain the status quo then.

**Comment by pgaskin** [comment]
Ok, sounds good.
